l1d_config:
  cache_size: 128
  block_size: 8
  associativity: 1

l1i_config:
  cache_size: 128
  block_size: 8
  associativity: 1

l2_config:
  cache_size: 512
  block_size: 16
  associativity: 1

scratch_pad_config:
  size: 256
  block_size: 64

inst_latencies:
  add: 1
  addi: 1
  sub: 1

cache_latencies:
  l1_hit: 1
  l1_miss: 4
  l2_hit: 3
  l2_miss: 9
  mem_access: 5